//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

pub use super::post::Entity as Post;
pub use super::search_queries::Entity as SearchQueries;
pub use super::supplements::Entity as Supplements;
